[package]
name = "mp4-presenter"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bevy_framepace = "0.17.1"
ffmpeg-next = "7.0.2"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
lto = true
